### ISSUE TITLE
Upstream integration of mouse fix into stock wine version

### ISSUE THREAD

**Issue by aryoda** [Frogging-Family/community-patches#103]
Would it be possible to integrate the fix into the normal wine version so that it is no longer needed to to apply the patch manually or install a separated patched version just for Roblox (which is a security risk if a binary wine version ist installed from any server)?

Patch:

https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/roblox_mouse_fix-fshack.mypatch

**Comment by Tk-Glitch** [comment]
The patch is incorrect and not very friendly to other apps, so it's not really a good candidate for default integration.

**Comment by aryoda** [comment]
Thanks for clarifying this!

I think some people like me may hope that one day the problem may be fixed in mainline/upstream wine which is unlikely as I understand now.

I suggest to document this somewhere (eg. in the [readme](https://github.com/Frogging-Family/community-patches) and [win-tkg-git repo](https://github.com/Frogging-Family/wine-tkg-git)) since this means that a patched wine version must always be side-installed.

Anyhow I will close this issue, thanks for your really valuable open source efforts (can't tell you how happy my daughter was that Roblox is running on Linux now ;-)

**Comment by Tk-Glitch** [comment]
Actually, an upstream fix isn't unlikely. After all, if it works on windows the goal should be too make it work on wine sooner or later. Now when will it be? Hard to tell. Roblox seems to have some very specific needs regarding mouse pointer handling, as the fix isn't known to help or fix anything else afaik.

**Comment by Tk-Glitch** [comment]
Whoops, wrong button 🐸

Maybe @rbernon would be interested in fixing this?

**Comment by rbernon** [comment]
I'm not sure to understand what this is about but the patch doesn't look right anyway.

**Comment by Tk-Glitch** [comment]
@rbernon The patch definitely isn't right. We're talking about https://bugs.winehq.org/show_bug.cgi?id=51301.

**Comment by aryoda** [comment]
OK, since there already is an existing ticket for the problem I would like to close this issue.

Sorry for the "noise", I should have checked the winehq tickets first.

**Comment by goldstar611** [comment]
I think Roblox pushed an update this week (possibly today) that fixes the mouse issue under wine.

**Comment by aryoda** [comment]
> I think Roblox pushed an update this week (possibly today) that fixes the mouse issue under wine.

Good news. Do you have a source (URL) for your information?
