### ISSUE TITLE
0002-proton_LFH.mypatch fails to apply

### ISSUE THREAD

**Issue by niobium93** [Frogging-Family/community-patches#117]
[wine-tkg-staging.log ](https://gist.github.com/niobium93/ec4aa3669e2e7b41999c3ab8bcf984ca)

**Comment by gardotd426** [comment]
I can confirm this, though since you (Etienne) have already added the bug label I'm assuming you have too.

**Comment by Tk-Glitch** [comment]
Upstream changes made it non-trivial to rebase. We'll probably have to wait until Proton is rebased. Alternatively, one can build against Valve trees for the time being.

**Comment by Tk-Glitch** [comment]
Rémi is working on it at his pace, but the patchset wasn't forgotten.

```
rbernon — 07/06/2022
yeah i was kind of working on that lately
though i paused it because now that i cleaned up the heap code i need to figure the right way to integrate the LFH
```
