### ISSUE TITLE
[wine-tkg-git] Can't applying guy1524_mfplat_WIP patch

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/community-patches#12]
Hi frogs,

As indicated by the title, the patch need update with the last commits.
Here is the errors logs : [patch_error.log](https://github.com/Frogging-Family/community-patches/files/4648679/patch_error.log)

Thanks for all you've done :100:

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/community-patches/commit/3765d5281af0b172237d62cd74a6370c840411fa
It was ready before staging rebase got pushed, but I really needed to sleep 🐸

**Comment by IroAlexis** [comment]
Ah ! The health before all ! Thanks :+1:
