### ISSUE TITLE
[Request] FSR2 Patch for Wine/Proton

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/community-patches#123]
FSR2 was open-sourced some time ago, supposedly; would be nice to have a patch for that for Wine to see how it compares to FSR1

**Comment by Tk-Glitch** [comment]
Not possible. FSR2.0 isn't a simple upscaler as FSR1.0 is and cannot be implemented in a generic way. It requires temporal data, jittering, motion vectors.. Like DLSS basically.

The [CyberFSR2 project](https://github.com/PotatoOfDoom/CyberFSR2), originally made specifically to inject FSR2.0 as a DLSS replacement in Cyberpunk 2077 is the closest thing there is to your request currently, and aims at becoming a "generic" replacement for DLSS 2.x that would be usable on GPUs with no DLSS support.

I have used it myself on Cyberpunk 2077 with great success as you can see below with a very zoomed in detail. The performance was basically the same between those shots:

FSR 1.0 ultraquality:
![FSR1 0-ultraquality](https://user-images.githubusercontent.com/741977/183632585-fa427b5d-ec00-48bf-bbe9-f955f43c7db9.png)

FSR2.0 quality:
![FSR2 0-quality](https://user-images.githubusercontent.com/741977/183632602-c45b262e-d705-4516-bc7d-8a3d0a4086e5.png)

**Comment by ThisNekoGuy** [comment]
Ah, I see... Okay; thanks for clarifying that for me, I was under the wrong impression about its implementation
