### ISSUE TITLE
How to ckeck that eevdf scheduler is active?

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/community-patches#150]
I have compiled the 6.5 kernel with eevdf scheduler. How can I check if the scheduler is active? I do not see any trace of eevdf in the journal.

**Comment by ptr1337** [comment]
> I have compiled the 6.5 kernel with eevdf scheduler. How can I check if the scheduler is active? I do not see any trace of eevdf in the journal.

EEVDF does not print anything. CFS also never did this.
EEVDF is a complete replacement for CFS, so it wont show anything.

You can check if the sysctl variables from cfs are not available as well as if the "base_slice" is present in `/sys/kernel/debug/sched`

**Comment by mabod** [comment]
ok. That helps. I see `base_slice_ns` and no `wakeup_granularity_ns` etc.
