### ISSUE TITLE
(Wine-TKG-Git) guy mfplat WIP failed to apply

### ISSUE THREAD

**Issue by ViNi-Arco** [Frogging-Family/community-patches#18]
Good afternoon Etienne, when applying the patch in Wine 5.6 exactly `staging version '4370386'` and `plain version '5e75310'` he fails with this error:

patching file tools/make_makefiles
patching file tools/makedep.c
Hunk #1 FAILED at 182.
Hunk #2 succeeded at 190 (offset 1 line).
Hunk #3 succeeded at 1373 (offset 1 line).
Hunk #5 succeeded at 4249 (offset 1 line).
1 out of 5 hunks FAILED -- saving rejects to file tools/makedep.c.rej
patching file dlls/mf/Makefile.in
Hunk #1 FAILED at 5.
1 out of 1 hunk FAILED -- saving rejects to file dlls/mf/Makefile.in.rej
patching file dlls/mf/handler.c
patching file dlls/mf/handler.h
patching file dlls/mf/main.c

>`makedep.c.rej:`
--- tools/makedep.c
+++ tools/makedep.c
@@ -182,6 +182,7 @@ struct makefile
     struct strarray install_lib;
     struct strarray install_dev;
     struct strarray extra_targets;
>+    struct strarray parent_dirs;
     struct strarray extra_imports;
     struct list     sources;
     struct list     includes;

> `Makefile.in.rej:`
--- dlls/mf/Makefile.in
+++ dlls/mf/Makefile.in
@@ -5,6 +5,7 @@ IMPORTS   = advapi32 mfplat ole32 uuid mfuuid
 EXTRADLLFLAGS = -mno-cygwin
> 
> C_SRCS = \
>+	handler.c \
 	evr.c \
 	main.c \
 	samplegrabber.c \

[prepare.log](https://github.com/Frogging-Family/community-patches/files/4961936/prepare.log)

Have a good day and take care of your health, even more in this difficult time

**Comment by Tk-Glitch** [comment]
You'll need an older version of the patch for 5.6. The first version of it, actually: https://github.com/Frogging-Family/community-patches/blob/6c804ff01bb688f49949ed6ce07419206f395e44/wine-tkg-git/guy1524_mfplat_WIP.mypatch
It's 2 days newer than 5.6 release. Hopefully it'll just werkz :tm:

**Comment by ViNi-Arco** [comment]
:grin: thankyou Etienne, you are a adorable person

**Comment by Tk-Glitch** [comment]
I didn't do much!
What an interesting day :relaxed: The adorable ones are the ones spreading that love.
