### ISSUE TITLE
Seems as though *part* of the mk11-gamepad-fix was upstreamed, now fails to apply

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/community-patches#24]
So I was building a new Proton for MK11 and I went to apply the gamepad patch, and it failed. I checked prepare.log, and this was what I saw:
```
Applying your own patch mk11-gamepad-fix.mypatch
patching file dlls/wbemprox/class.c
Hunk #1 succeeded at 411 with fuzz 2 (offset 295 lines).
Hunk #2 FAILED at 125.
1 out of 2 hunks FAILED -- saving rejects to file dlls/wbemprox/class.c.rej
```
Offending code:
```

     *puReturned = 0;
-    if (ec->index >= view->result_count) return WBEM_S_FALSE;
-
-    table = get_view_table( view, ec->index );
-    hr = create_class_object( table->name, iface, ec->index, NULL, apObjects );
-    if (hr != S_OK) return hr;
-
-    ec->index++;
-    *puReturned = 1;
-    if (ec->index == view->result_count && uCount > 1) return WBEM_S_FALSE;
-    if (uCount > 1) return WBEM_S_TIMEDOUT;
+
+    for (i=0; i<uCount; ++i)
+    {
+        if (ec->index >= view->result_count) return WBEM_S_FALSE;
+        table = get_view_table( view, ec->index );
+        hr = create_class_object( table->name, iface, ec->index, NULL, apObjects );
+        if (hr != S_OK) return hr;
+
+        apObjects++;
+        ec->index++;
+        ++*puReturned;
+    }
     return WBEM_S_NO_ERROR;
 }
```
Which is the second of the two parts of the patch. looking in `dlls/wbemprox/class.c`, there is almost identical code in that spot: 

```
    if (lTimeout != WBEM_INFINITE && !once++) FIXME("timeout not supported\n");

    *puReturned = 0;

    for (i = 0; i < uCount; i++)
    {
        if (ec->index >= view->result_count) return WBEM_S_FALSE;
        table = get_view_table( view, ec->index );
        hr = create_class_object( table->name, iface, ec->index, NULL, &apObjects[i] );
        if (hr != S_OK)
        {
            for (j = 0; j < i; j++) IWbemClassObject_Release( apObjects[j] );
            return hr;
        }
        ec->index++;
        (*puReturned)++;
    }

    return WBEM_S_NO_ERROR;
}
```

There are a couple formatting changes and some I-don't-know-if-they're-consequential-but-I'm-sure-you-will extremely minor tweaks that might also just be formatting, but yeah. Figured I'd let you know so you could just chop that part out or whatever else is appropriate, I removed the offending half of the patch and am running the build again, will report if the gamepad works, or doesn't (assuming MK11 actually works for me lol). I didn't want to file a PR because for 1 I'm sure you're sleeping at this time of night in France and 2, I don't know if you even want to just remove that part of the patch. Trying not to create unnecessary hassle for you.

**Comment by gardotd426** [comment]
Welp. I guess it doesn't matter, because the latest update broke MK11 completely anyway. 

I've tried with the previous 5.9 TKG build I was using (that definitely worked), as well as GE's 5.11-GE-3-MF which is known to (used to) work. 

The little splash window pops up, and stays there forever. You have to kill it to make it go away. DX11 and DX12. AMDVLK and vulkan-amdgpu-pro. I'm going to make a post on the Proton GitHub but it's not as if anyone there will do anything.

**Comment by Tk-Glitch** [comment]
The mk11 gamepad fix was upstreamed with https://github.com/wine-mirror/wine/commit/84d85adeea578cac37bded97984409f44c7985ba

See: https://github.com/Frogging-Family/wine-tkg-git/commit/22f1ef64b3d0bec4e724b203f1e87a5522af76bb#diff-8cdeb58bafdc2f0a46c6ad4631a22199

**Comment by gardotd426** [comment]
Ahh, I didn't the first hunk in the class.c file, so I figured that much hadn't been upstreamed, but I also didn't see that you'd added that part to the mk11.patch in wine-tkg-patches, and I thought you might remove the gamepad patch if it's no longer needed, but then again, I guess if someone's using _localbuild or a custom repo targeting an older version of Wine then they still might need it. I'll close, thanks.

**Comment by Tk-Glitch** [comment]
It's still there as legacy patches for earlier trees. Like virtually all the patches I offre 🐸
