### ISSUE TITLE
Failed to apply guy1524_mfplat_WIP.mypatch

### ISSUE THREAD

**Issue by oscarwallberg** [Frogging-Family/community-patches#25]
Failing to apply guy1524_mfplat_WIP.mypatch on proton-tkg. Please find the log file attached.

[prepare.log](https://github.com/Frogging-Family/community-patches/files/5214983/prepare.log)

**Comment by Tk-Glitch** [comment]
The patchset is being staged and upstreamed lately, deprecating the WIP patchset. I have now removed it as a result.
