### ISSUE TITLE
zstd.mypatch not working with zstd module compression

### ISSUE THREAD

**Issue by veganvelociraptor** [Frogging-Family/community-patches#26]
I don't think I've ever managed to get this patch to work when switching on MODULE_COMPRESS_ZSTD.

It seems something within mkinitcpio still insists on only accepting modules with the .gz suffix, and every attempt I've made results in the same message when compiling the kernel, "No modules were added to the image. This is probably not what you want."

Compressing the kernel image with zstd works just fine, but the module compression doesn't work for me.

**Comment by Snoop05** [comment]
you need kmod and mkinitcpio patched too

**Comment by veganvelociraptor** [comment]
Thanks. I already had mkinitcpio patched but didn't think of km od.
