### ISSUE TITLE
[wine-tkg-git] Does not apply amdags.mypatch

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/community-patches#28]
Hello TkG,

Like describe in the title, here is the [prepare.log](https://github.com/Frogging-Family/community-patches/files/5408972/prepare.log).

As always, thank you for everything :frog:

**Comment by Tk-Glitch** [comment]
Enabling `_msvcrt_nativebuiltin` will make it work. Either I remove those changes (which are registry entries for wolfenstein new colossus and RDR2) or I add it as a prerequisite in the readme.

**Comment by IroAlexis** [comment]
Hmmm despite `_msvcrt_nativebuiltin` enabling, the patch doesn't apply... From scratch, same thing.

For me, you should do the same as for the others (winex11-fs-no_above_state.mypatch, etc...) add it in the readme

**Comment by Tk-Glitch** [comment]
Oh wait, it's not a proton build. That's why. I'll move those bits to steam-bits then.

**Comment by IroAlexis** [comment]
Yeah it is good and I should have specified that it was a wine-tkg build my bad. Thanks you TkG :frog:

**Comment by Tk-Glitch** [comment]
I should have noticed earlier :frog:
