### ISSUE TITLE
amd_ags_x64_main.c:2: error: system header stdbool.h cannot be used with msvcrt

### ISSUE THREAD

**Issue by Sukid** [Frogging-Family/community-patches#29]
I realize an issue with amdags and msvcrt was fixed a while back, but now I'm getting this problem when I try to apply it.
`../wine-mirror-git/dlls/amd_ags_x64/amd_ags_x64_main.c:2: error: system header stdbool.h cannot be used with msvcrt`

Doesn't matter whether I enable or disable the msvcrt proton patch, same thing happens. Prepare.log doesn't seem to complain about it, although it does show a bunch of unhandled chain conversions for vulkan which may or may not be relevant at all.

**Comment by Tk-Glitch** [comment]
I have tried and tried, but I'm totally unable to reproduce your issue. Could you please give more detail about your setup?

**Comment by Sukid** [comment]
hmmm... I have up to date gcc, I've tried installing normal wine-staging in case that would affect it. I also tried clearing ccache, and cloning wine-tkg-git and community-patches to my SSD instead of the hdd I normally clone everything to.  Not sure what other factors would effect it. Anything I can bring up to give you the info you're looking for? Would Mesa have any effect on this?

**Comment by Tk-Glitch** [comment]
> is based on staging 5.9

Oh. That is extremely likely to be the issue. For such an old version you'll want to use the previous patchset: https://raw.githubusercontent.com/Frogging-Family/community-patches/f43839ed2e416aec892c13e22048ab300ff1923f/wine-tkg-git/amdags.mypatch
Drop it in you userpatches dir and remove the community patch from your .cfg. You should be good to go afterwards.

**Comment by Sukid** [comment]
all right, that did it! Thanks a bunch!! :D

**Comment by Tk-Glitch** [comment]
You're welcome!
