### ISSUE TITLE
ntdll_Map_top-down_if_dll_characteristics_include_DYNAMIC_BASE.mypatch

### ISSUE THREAD

**Issue by ManuLinares** [Frogging-Family/community-patches#38]
not working

https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/ntdll_Map_top-down_if_dll_characteristics_include_DYNAMIC_BASE.mypatch

relevant files in https://github.com/ValveSoftware/Proton/issues/170#issuecomment-769492896

new working patch 
[ntdll_Map_top-down_if_dll_characteristics_include_DYNAMIC_BASE.mypatch.txt](https://github.com/Frogging-Family/community-patches/files/5891493/ntdll_Map_top-down_if_dll_characteristics_include_DYNAMIC_BASE.mypatch.txt)

tested with latest wine-tkg-git, and latest  "[skse64_2_00_19.7z](https://skse.silverlock.org/beta/skse64_2_00_19.7z)"

**Comment by Tk-Glitch** [comment]
Thanks! I'll update the patchset with your changes.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/community-patches/commit/cdcd4c6edd1ecd515e418c352211e99597ea94bd
