### ISSUE TITLE
kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM-staging fails to apply

### ISSUE THREAD

**Issue by Ember2528** [Frogging-Family/community-patches#49]
When attempting to apply the GMEM_MOVEABLE patch to the latest wine-staging the patch fails to apply

>Applying your own patch kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM-staging.mypatch
>patching file dlls/kernel32/heap.c
>Hunk #1 succeeded at 155 (offset -57 lines).
>Hunk #2 succeeded at 225 (offset -57 lines).
>Hunk #3 succeeded at 239 (offset -57 lines).
>Hunk #4 succeeded at 318 (offset -57 lines).
>Hunk #5 FAILED at 387.
>Hunk #6 FAILED at 398.
>Hunk #7 succeeded at 416 (offset -57 lines).
>Hunk #8 succeeded at 426 (offset -57 lines).
>2 out of 8 hunks FAILED -- saving rejects to file dlls/kernel32/heap.c.rej
>patching file dlls/kernel32/tests/heap.c
>Hunk #1 succeeded at 334 (offset -3 lines).
>patching file dlls/kernelbase/kernelbase.spec
>Hunk #1 succeeded at 1777 (offset 8 lines).
>patching file dlls/kernelbase/memory.c
>Hunk #1 succeeded at 537 (offset 152 lines).
>Hunk #2 succeeded at 703 (offset 152 lines).
>Hunk #3 succeeded at 758 (offset 152 lines).
>Hunk #4 succeeded at 898 (offset 165 lines).
>Hunk #5 succeeded at 950 (offset 165 lines).
>patching file include/winbase.h
>Hunk #1 succeeded at 2919 with fuzz 2 (offset 4 lines).

**Comment by llde** [comment]
Use the non staging version for recent wine-staging releases

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/community-patches/commit/34572d634ab54d1bcff444d635d3bb6af16db231
