### ISSUE TITLE
[dxvk] Can't apply rainbow_hud.dxvkpatch 

### ISSUE THREAD

**Issue by llde** [Frogging-Family/community-patches#50]
patching file src/dxvk/hud/dxvk_hud_renderer.cpp
Hunk #2 succeeded at 19 (offset 1 line).
Hunk #3 succeeded at 42 with fuzz 2 (offset 1 line).
Hunk #4 succeeded at 93 with fuzz 2 (offset 4 lines).
patching file src/dxvk/hud/dxvk_hud_renderer.h
Hunk #2 FAILED at 88.
Hunk #3 succeeded at 149 (offset 18 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/dxvk/hud/dxvk_hud_renderer.h.rej

**Comment by Tk-Glitch** [comment]
I'm not sure Josh had any plan for maintaining this :frog:
I'll see what I can do.

**Comment by llde** [comment]
I rebaesd it myself, pull request incoming
