### ISSUE TITLE
There is no info in either community-patches or wine-tkg-git readmes on where community patches should be placed

### ISSUE THREAD

**Issue by Gagis** [Frogging-Family/community-patches#6]
I'm going to assume its supposed to be cloned in same directory as where wine-tkg-git was cloned, but this would be very nice to have actually be written somewhere.

**Comment by Tk-Glitch** [comment]
Yeah it'll search for it at the place it is in the PKGBUILDS repo: https://github.com/Tk-Glitch/PKGBUILDS
I have plans to make this smoother and simpler very soon.
