### ISSUE TITLE
FSR patch is broken

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/community-patches#86]
NOTE: While I was typing this, wine-staging itself got updated and rebased against 7.0-rc1 so everything is broken right now, but amd_fsr_hack still needs to be rebased, so I'm still filing this anyway

I was trying to build in my usual wine-tkg-git repo directory, and it kept failing wine winevulkan errors. So I did a fresh git clone, built with defaults, and it built fine. I started removing stuff one by one, and figured out that `amd_fsr_fshack.mypatch` in `_community_patches=` was the culprit. It applies fine, but it causes a build failure.

There have been a ton of winevulkan commits in upstream wine, so that's probably why. I haven't had the time to bisect which upstream commit breaks it, but I'll try to get on that asap. 

On a similar note, if it wouldn't be too difficult, I think `wine-tkg-userpatches` (or the build script in general) should be modified to allow for either:

 - using *both* `_plain_version=` and `_staging_version=` on staging builds. I am unable to easily bisect which plain wine commit broke FSR because fshack isn't allowed on plain wine builds, and you can't specify `_plain_version` on staging builds. But since there have been several winevulkan commits to plain wine in between the working and broken staging commits, it's impossible for me to find out which one broke it (at least not without a huge amount of hassle). 
 
- being able to patch the plain wine tree with wine-tkg-userpatches **before** the wine-staging patches get applied. I used `git format-patch` to create patches to revert the 3 commits I suspected, but none of them would apply when placed in `wine-tkg-userpatches` because they could only be applied *after* the staging and hotfixer stuff, which meant that they could no longer cleanly apply. 

I hope either of those suggestions at least make sense as to what I'm actually asking. 

But anyway, yeah somewhere between staging commits 2653c32 and 155e98e, the FSR patch got brokeded and won't apply. 

Obviously I know that your priority will probably be fixing the script and hotfixer for 7.0-rc1 since now you can't build anything targeting current wine-staging, but still, just wanted to make the report.

**Comment by Tk-Glitch** [comment]
I have pinged DadSchoorse about it. It's weird it complains about exp2f when math.h is in the includes. Clearly I'm missing something Dad will probably be able to help with.

**Comment by GloriousEggroll** [comment]
fix thanks to openglfreak -- 
```
diff --git a/dlls/winevulkan/Makefile.in b/dlls/winevulkan/Makefile.in
index 38809211308..f7ca282921f 100644
--- a/dlls/winevulkan/Makefile.in
+++ b/dlls/winevulkan/Makefile.in
@@ -2,7 +2,7 @@ MODULE    = winevulkan.dll
 UNIXLIB   = winevulkan.so
 IMPORTLIB = winevulkan
 IMPORTS   = user32 gdi32 advapi32 setupapi win32u
-EXTRALIBS = $(PTHREAD_LIBS)
+EXTRALIBS = -lm $(PTHREAD_LIBS)

 C_SRCS = \
 	loader.c \
```
